# Generated by Django 5.1.1 on 2025-09-22 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("summary", models.TextField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("topics", models.JSONField(default=list)),
                ("sentiment", models.CharField(max_length=20)),
                ("keywords", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
