# Generated by Django 5.1.1 on 2025-09-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="confidence",
            field=models.FloatField(default=0.0),
        ),
    ]
